### ISSUE TITLE
主程序检查大文件不能发现违禁词

### ISSUE THREAD

**Issue by kangxuwinsun** [SouthUp/CiniuWindowsClient#22]
word文件（超6000字）较大，主程序不能识别，插件可以；
2万字文档，20秒时间搜索完毕，搜索中编辑文档略微卡顿；
百万字文档，搜索过程近乎卡死。
千字文档，秒搜完毕。

违禁词多的文档（1000个违禁词）花费时间50秒。

**Comment by FullHouse2222** [comment]
V1版本解决方案：增加报错弹框提示
